"""
Kaggle CPU check, generated by scripts/kaggle_ops.py: the IG-65M R(2+1)D-34
weights download and load strictly into cuhkx's architecture with the
4-channel Depth+IR stem, before a GPU session is spent on it.
"""
import base64
import os
import sys
import time

SRC = {}           # @@SRC@@

WORK = "/kaggle/working" if os.path.isdir("/kaggle/working") else os.getcwd()
os.chdir(WORK)
for name, b64 in SRC.items():
    with open(os.path.join(WORK, name), "wb") as f:
        f.write(base64.b64decode(b64))
sys.path.insert(0, WORK)

import torch  # noqa: E402

import cuhkx  # noqa: E402

t = time.time()
cuhkx.prefetch("r2plus1d_34")
print(f"prefetch {time.time() - t:.0f}s", flush=True)
cfg = cuhkx.Cfg(modality="DepthIR_PC", arch="r2plus1d_34", frames=16, size=128)
net = cuhkx.make_model(cfg, pretrained=True).eval()
n = sum(p.numel() for p in net.parameters())
w = net.backbone.stem[0].weight
print(f"params {n / 1e6:.2f} M | stem {tuple(w.shape)}", flush=True)
assert torch.allclose(w[:, 3], w[:, :3].mean(1), atol=1e-6)
with torch.no_grad():
    t = time.time()
    y = net(torch.randn(2, 16, 4, 128, 128))
print("out", tuple(y.shape), f"| forward {time.time() - t:.1f}s for 2 clips on CPU", flush=True)
print("ARCHCHECK OK")
