"""
CUHK-X person detection — Kaggle CPU kernel, generated by scripts/kaggle_ops.py.

Runs torchvision's COCO SSDlite320-MobileNetV3 on a few native-resolution IR
frames per clip and writes one crop box per clip. prep.py is embedded below
(the SRC line), and every step (fp32 detector, frame decoding, person
selection, the box rule) is a prep.py function that infer.py calls
identically at test time.

Output /kaggle/working/person_boxes.parquet: one row per clip with the box
(x0..y1, -1 = no person: keep the full frame) and the raw per-frame
detections (`dets`, JSON, persons scoring >= 0.05), so the box rule can be
re-tuned locally without another detection run.
"""
import base64
import glob
import json
import os
import sys
import time

SRC = {}           # @@SRC@@

T0 = time.time()
WORK = "/kaggle/working" if os.path.isdir("/kaggle/working") else os.getcwd()
os.chdir(WORK)
for name, b64 in SRC.items():
    with open(os.path.join(WORK, name), "wb") as f:
        f.write(base64.b64decode(b64))
sys.path.insert(0, WORK)

import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
import torch  # noqa: E402

import prep  # noqa: E402

torch.set_grad_enabled(False)
torch.set_num_threads(os.cpu_count() or 4)
BATCH = 16
RAW_SCORE = 0.05


def log(*a):
    print(f"[{(time.time() - T0) / 60:6.1f}m]", *a, flush=True)


src = None
for mj in glob.glob("/kaggle/input/**/modality.json", recursive=True):
    if json.load(open(mj)).get("modality") == "IRdet":
        src = os.path.dirname(mj)
if src is None:
    raise SystemExit("IRdet dataset not attached")
idx = pd.read_parquet(os.path.join(src, "index.parquet"))
weights = sorted(glob.glob(os.path.join(src, "ssdlite*.pth")))
if not weights:
    raise SystemExit("SSDlite weights missing from the IRdet dataset")
dev = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = prep.make_detector(torch.load(weights[0], map_location="cpu")).to(dev)
log(f"{len(idx)} clips, {int(idx.t.sum())} frames | device {dev} | cpus {os.cpu_count()}")

handles = {}


def read(blob, off, ln):
    f = handles.get(blob)
    if f is None:
        f = handles[blob] = open(os.path.join(src, f"blob_{int(blob):03d}.bin"), "rb")
    f.seek(int(off))
    return f.read(int(ln))


dets = {}          # clip row -> per frame: best person (x0, y0, x1, y1, score) or None
batch, owners = [], []


def flush():
    if not batch:
        return
    outs = model([b.to(dev) for b in batch])
    for i, o in zip(owners, outs):
        dets.setdefault(i, []).append(
            prep.best_person({k: v.cpu() for k, v in o.items()}, score=RAW_SCORE))
    batch.clear()
    owners.clear()


for i, r in enumerate(idx.itertuples(index=False)):
    for off, ln in zip(r.offsets, r.lengths):
        x = prep.det_input(read(r.blob, off, ln))
        if x is None:
            dets.setdefault(i, []).append(None)
            continue
        batch.append(x)
        owners.append(i)
        if len(batch) >= BATCH:
            flush()
    if (i + 1) % 500 == 0:
        log(f"{i + 1}/{len(idx)} clips")
flush()

rows = []
for i, r in enumerate(idx.itertuples(index=False)):
    raw = dets.get(i, [])
    # best_person at RAW_SCORE, then the DET_SCORE cut: the same person
    # prep.best_person(out) returns with its default threshold.
    fb = [b if b is not None and b[4] >= prep.DET_SCORE else None for b in raw]
    box = prep.person_box(fb, (int(r.h), int(r.w)))
    hits = [b for b in fb if b is not None]
    rows.append(dict(clip_id=r.clip_id, split=r.split, frames=len(fb), hits=len(hits),
                     score=float(np.mean([b[4] for b in hits])) if hits else 0.0,
                     x0=box[0] if box else -1, y0=box[1] if box else -1,
                     x1=box[2] if box else -1, y1=box[3] if box else -1,
                     h=int(r.h), w=int(r.w),
                     dets=json.dumps([None if b is None else [round(v, 2) for v in b]
                                      for b in raw])))
out = pd.DataFrame(rows)
out.to_parquet(os.path.join(WORK, "person_boxes.parquet"), index=False)
found = out.x0 >= 0
side = (out.x1 - out.x0)[found] / out.h[found]
log(f"boxes for {int(found.sum())}/{len(out)} clips ({100 * found.mean():.1f}%); "
    f"test {int(found[out.split == 'test'].sum())}/{int((out.split == 'test').sum())}; "
    f"crop side / frame height p10 {side.quantile(.1):.2f} p50 {side.median():.2f} "
    f"p90 {side.quantile(.9):.2f}")
log("done")
