"""
CUHK-X IMU stream — Kaggle CPU kernel, generated by scripts/kaggle_ops.py.

Writes the embedded library (the SRC line), finds the packed IMU dataset by its
modality.json marker, and runs imu_train.py: the 1-D ResNet on every
user-grouped fold plus all training users. Outputs land in /kaggle/working.
"""
import base64
import glob
import json
import os
import subprocess
import sys
import time

SRC = {}           # @@SRC@@

WORK = "/kaggle/working" if os.path.isdir("/kaggle/working") else os.getcwd()
os.chdir(WORK)
for name, b64 in SRC.items():
    with open(os.path.join(WORK, name), "wb") as f:
        f.write(base64.b64decode(b64))

data = next((os.path.dirname(m) for m in glob.glob("/kaggle/input/**/modality.json", recursive=True)
             if json.load(open(m)).get("modality") == "IMU"), None)
if data is None:
    raise SystemExit("IMU dataset not attached")
t0 = time.time()
cmd = [sys.executable, "imu_train.py", "--data", data, "--out", WORK,
       "--threads", str(os.cpu_count() or 4), "--epochs", "80"]
print("RUN", " ".join(cmd), flush=True)
rc = subprocess.call(cmd, env=dict(os.environ, PYTHONPATH=WORK))
print(f"imu_train exit {rc} after {(time.time() - t0) / 60:.1f} min", flush=True)
sys.exit(rc)
